use crate::args::types::{DayVal, MinorDays, Name};
use chrono::prelude::*;
use chrono::Duration;
use heca_lib::prelude::HebrewMonth;
use heca_lib::HebrewYear;
use std::num::NonZeroI8;

//generated from https://play.golang.com/p/fCtYz6kNCBw
pub fn get_omer(year: &HebrewYear) -> [DayVal; 49] {
    let first_day_of_pesach: DateTime<Utc> = year
        .get_hebrew_date(HebrewMonth::Nissan, NonZeroI8::new(15).unwrap())
        .unwrap()
        .into();

    //generated by https://play.golang.org/p/G78vf0EJnCN
    [
        DayVal {
            day: first_day_of_pesach + Duration::days(1),
            name: Name::MinorDays(MinorDays::Omer1),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(2),
            name: Name::MinorDays(MinorDays::Omer2),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(3),
            name: Name::MinorDays(MinorDays::Omer3),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(4),
            name: Name::MinorDays(MinorDays::Omer4),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(5),
            name: Name::MinorDays(MinorDays::Omer5),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(6),
            name: Name::MinorDays(MinorDays::Omer6),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(7),
            name: Name::MinorDays(MinorDays::Omer7),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(8),
            name: Name::MinorDays(MinorDays::Omer8),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(9),
            name: Name::MinorDays(MinorDays::Omer9),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(10),
            name: Name::MinorDays(MinorDays::Omer10),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(11),
            name: Name::MinorDays(MinorDays::Omer11),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(12),
            name: Name::MinorDays(MinorDays::Omer12),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(13),
            name: Name::MinorDays(MinorDays::Omer13),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(14),
            name: Name::MinorDays(MinorDays::Omer14),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(15),
            name: Name::MinorDays(MinorDays::Omer15),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(16),
            name: Name::MinorDays(MinorDays::Omer16),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(17),
            name: Name::MinorDays(MinorDays::Omer17),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(18),
            name: Name::MinorDays(MinorDays::Omer18),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(19),
            name: Name::MinorDays(MinorDays::Omer19),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(20),
            name: Name::MinorDays(MinorDays::Omer20),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(21),
            name: Name::MinorDays(MinorDays::Omer21),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(22),
            name: Name::MinorDays(MinorDays::Omer22),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(23),
            name: Name::MinorDays(MinorDays::Omer23),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(24),
            name: Name::MinorDays(MinorDays::Omer24),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(25),
            name: Name::MinorDays(MinorDays::Omer25),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(26),
            name: Name::MinorDays(MinorDays::Omer26),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(27),
            name: Name::MinorDays(MinorDays::Omer27),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(28),
            name: Name::MinorDays(MinorDays::Omer28),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(29),
            name: Name::MinorDays(MinorDays::Omer29),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(30),
            name: Name::MinorDays(MinorDays::Omer30),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(31),
            name: Name::MinorDays(MinorDays::Omer31),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(32),
            name: Name::MinorDays(MinorDays::Omer32),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(33),
            name: Name::MinorDays(MinorDays::Omer33),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(34),
            name: Name::MinorDays(MinorDays::Omer34),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(35),
            name: Name::MinorDays(MinorDays::Omer35),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(36),
            name: Name::MinorDays(MinorDays::Omer36),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(37),
            name: Name::MinorDays(MinorDays::Omer37),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(38),
            name: Name::MinorDays(MinorDays::Omer38),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(39),
            name: Name::MinorDays(MinorDays::Omer39),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(40),
            name: Name::MinorDays(MinorDays::Omer40),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(41),
            name: Name::MinorDays(MinorDays::Omer41),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(42),
            name: Name::MinorDays(MinorDays::Omer42),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(43),
            name: Name::MinorDays(MinorDays::Omer43),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(44),
            name: Name::MinorDays(MinorDays::Omer44),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(45),
            name: Name::MinorDays(MinorDays::Omer45),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(46),
            name: Name::MinorDays(MinorDays::Omer46),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(47),
            name: Name::MinorDays(MinorDays::Omer47),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(48),
            name: Name::MinorDays(MinorDays::Omer48),
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(49),
            name: Name::MinorDays(MinorDays::Omer49),
        },
    ]
}
