use std::borrow::Cow;
use zmanim::prelude::tz::africa::*;
use zmanim::prelude::tz::america::*;
use zmanim::prelude::tz::asia::*;
use zmanim::prelude::tz::australia::*;
use zmanim::prelude::tz::europe::*;
use zmanim::prelude::tz::*;

//based on https://en.wikipedia.org/wiki/Jewish_population_by_country
pub const CITIES: [City; 50] = [
    City {
        name: Cow::Borrowed("NewYorkCity"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 40.7128,
        longitude: -74.0060,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Jerusalem"),
        time_zone: TimeZone::Asia(Asia::Jerusalem),
        latitude: 31.7683,
        longitude: 35.2137,
        candlelighting_to_sunset: 40,
    },
    City {
        name: Cow::Borrowed("LosAngeles"),
        time_zone: TimeZone::America(America::LosAngeles),
        latitude: 34.0522,
        longitude: -118.2437,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("TelAvivYafo"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 32.0853,
        longitude: 34.7818,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("SanFrancisco"),
        time_zone: TimeZone::America(America::LosAngeles),
        latitude: 37.3875,
        longitude: -122.0575,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Chicago"),
        time_zone: TimeZone::America(America::Chicago),
        latitude: 41.8781,
        longitude: -87.6298,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Paris"),
        time_zone: TimeZone::Europe(Europe::Paris),
        latitude: 41.8566,
        longitude: -2.3522,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Boston"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 42.3601,
        longitude: -71.0589,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("BuenosAires"),
        time_zone: TimeZone::America(America::BuenosAires),
        latitude: -34.6037,
        longitude: -58.3816,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("RishonLeZiyyon"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 31.9730,
        longitude: 34.7925,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("PetahTiqwa"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 32.0840,
        longitude: 34.8878,
        candlelighting_to_sunset: 40,
    },
    City {
        name: Cow::Borrowed("Haifa"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 32.7940,
        longitude: 34.9896,
        candlelighting_to_sunset: 30,
    },
    City {
        name: Cow::Borrowed("WashingtonDC"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 38.9072,
        longitude: -77.0369,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Philadelphia"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 39.9526,
        longitude: -75.1652,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Ashdod"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 31.8044,
        longitude: 34.6553,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Netanya"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 32.3215,
        longitude: 34.8532,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("BeerSheva"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 31.2530,
        longitude: 34.7915,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("London"),
        time_zone: TimeZone::Europe(Europe::London),
        latitude: 51.5074,
        longitude: -0.1278,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("RamatGan"),
        time_zone: TimeZone::Asia(Asia::TelAviv),
        latitude: 32.0684,
        longitude: 34.8248,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Atlanta"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 33.7490,
        longitude: -84.3880,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Miami"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 25.7617,
        longitude: -80.1918,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Toronto"),
        time_zone: TimeZone::America(America::Toronto),
        latitude: 43.6532,
        longitude: -79.3832,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Moscow"),
        time_zone: TimeZone::Europe(Europe::Moscow),
        latitude: 55.7558,
        longitude: 37.6173,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("SanDiego"),
        time_zone: TimeZone::America(America::LosAngeles),
        latitude: 32.7157,
        longitude: -117.1611,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Baltimore"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 39.2904,
        longitude: -76.6122,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Montreal"),
        time_zone: TimeZone::America(America::Toronto),
        latitude: 45.5017,
        longitude: -73.5673,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Cleveland"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 41.4993,
        longitude: -81.6994,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Denver"),
        time_zone: TimeZone::America(America::Denver),
        latitude: 39.7392,
        longitude: -104.9903,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Phoenix"),
        time_zone: TimeZone::America(America::Phoenix),
        latitude: 33.4484,
        longitude: -112.0740,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("LasVegas"),
        time_zone: TimeZone::America(America::LosAngeles),
        latitude: 36.1699,
        longitude: -115.1398,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Budapest"),
        time_zone: TimeZone::Europe(Europe::Budapest),
        latitude: 47.4979,
        longitude: 19.0402,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Detroit"),
        time_zone: TimeZone::America(America::Detroit),
        latitude: 42.3314,
        longitude: 83.0458,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("SaoPaulo"),
        time_zone: TimeZone::America(America::SaoPaulo),
        latitude: -23.5505,
        longitude: -46.6333,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Marseille"),
        time_zone: TimeZone::Europe(Europe::Paris),
        latitude: 43.2965,
        longitude: 5.3698,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Seattle"),
        time_zone: TimeZone::America(America::LosAngeles),
        latitude: 47.6062,
        longitude: -122.3321,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Lakewood"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 40.0821,
        longitude: -74.2097,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Dallas"),
        time_zone: TimeZone::America(America::Chicago),
        latitude: 32.7767,
        longitude: -96.7970,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("StLouis"),
        time_zone: TimeZone::America(America::Chicago),
        latitude: 38.6270,
        longitude: -90.1994,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Tampa"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 27.9506,
        longitude: -82.4572,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Johanneburg"),
        time_zone: TimeZone::Africa(Africa::Johannesburg),
        latitude: -26.2041,
        longitude: 28.0473,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Houston"),
        time_zone: TimeZone::America(America::Chicago),
        latitude: 29.7604,
        longitude: -95.3698,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Portland"),
        time_zone: TimeZone::America(America::LosAngeles),
        latitude: 45.5051,
        longitude: -122.6750,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Pittsburg"),
        time_zone: TimeZone::America(America::NewYork),
        latitude: 40.4406,
        longitude: -79.9959,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Melbourne"),
        time_zone: TimeZone::Australia(Australia::Melbourne),
        latitude: -37.8136,
        longitude: 144.9631,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Minneapolis"),
        time_zone: TimeZone::America(America::Chicago),
        latitude: 44.9778,
        longitude: -93.2650,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("PetersburgRussia"),
        time_zone: TimeZone::Europe(Europe::Moscow),
        latitude: 59.9343,
        longitude: 30.3351,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("RioDeJaneiro"),
        time_zone: TimeZone::America(America::SaoPaulo),
        latitude: -22.9068,
        longitude: -43.1729,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("MexicoCity"),
        time_zone: TimeZone::America(America::MexicoCity),
        latitude: 19.4326,
        longitude: -99.1332,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Sydney"),
        time_zone: TimeZone::Australia(Australia::Sydney),
        latitude: -33.8688,
        longitude: 151.2093,
        candlelighting_to_sunset: 18,
    },
    City {
        name: Cow::Borrowed("Hartford"),
        time_zone: TimeZone::Europe(Europe::Moscow),
        latitude: 41.7658,
        longitude: -72.6734,
        candlelighting_to_sunset: 18,
    },
    /*
    Vaughan,
    NewHaven,
    Cincinatti,
    Vancouver,
    Milwakki,
    Columbus,
    Manchester,
    Berlin,
    Tucson,
    Rochester,
    KiryasYoel,
    Creteil
    CoteStLuc,
    Montevido,
    Amsterdam,
    KansasCity,
    Orlando,
    Teaneck,
    Kiev,
    Istambul,
    Austin,
    Strassburg,
    Capetown,
    Sarcelles,*/
];

pub struct City {
    pub name: Cow<'static, str>,
    pub time_zone: TimeZone,
    pub latitude: f64,
    pub longitude: f64,
    pub candlelighting_to_sunset: u8,
}
