use crate::algorithms::minor_days::types::MinorDays;
use crate::args::types::{DayVal, Language, Name};
use crate::prelude::MyToString;
use chrono::{DateTime, Duration, Utc};
use heca_lib::{prelude::HebrewMonth, HebrewYear};

impl MinorDays {
    pub(crate) fn to_json_string(&self) -> &'static str {
        use MinorDays::*;
        match &self {
            Omer1 => "Omer1",
            Omer2 => "Omer2",
            Omer3 => "Omer3",
            Omer4 => "Omer4",
            Omer5 => "Omer5",
            Omer6 => "Omer6",
            Omer7 => "Omer7",
            Omer8 => "Omer8",
            Omer9 => "Omer9",
            Omer10 => "Omer10",
            Omer11 => "Omer11",
            Omer12 => "Omer12",
            Omer13 => "Omer13",
            Omer14 => "Omer14",
            Omer15 => "Omer15",
            Omer16 => "Omer16",
            Omer17 => "Omer17",
            Omer18 => "Omer18",
            Omer19 => "Omer19",
            Omer20 => "Omer20",
            Omer21 => "Omer21",
            Omer22 => "Omer22",
            Omer23 => "Omer23",
            Omer24 => "Omer24",
            Omer25 => "Omer25",
            Omer26 => "Omer26",
            Omer27 => "Omer27",
            Omer28 => "Omer28",
            Omer29 => "Omer29",
            Omer30 => "Omer30",
            Omer31 => "Omer31",
            Omer32 => "Omer32",
            Omer33 => "Omer33",
            Omer34 => "Omer34",
            Omer35 => "Omer35",
            Omer36 => "Omer36",
            Omer37 => "Omer37",
            Omer38 => "Omer38",
            Omer39 => "Omer39",
            Omer40 => "Omer40",
            Omer41 => "Omer41",
            Omer42 => "Omer42",
            Omer43 => "Omer43",
            Omer44 => "Omer44",
            Omer45 => "Omer45",
            Omer46 => "Omer46",
            Omer47 => "Omer47",
            Omer48 => "Omer48",
            Omer49 => "Omer49",
            ErevYomKippur => "ErevYomKippur",
            ErevSukkos => "ErevSukkos",
            ErevPesach => "ErevPesach",
            PesachSheni => "PesachSheni",
            LagBaOmer => "LagBaOmer",
            ErevShavuos => "ErevShavuos",
            ErevRoshHashanah => "ErevRoshHashanah",
            FifteenShvat => "FifteenShvat",
            FifteenAv => "FifteenAv",
            PurimKattan => "PurimKattan",
            ShushanPurimKattan => "ShushanPurimKattan",
            ShabbosHaGadol => "ShabbosHaGadol",
            TaanisBechoros => "TaanisBechoros",
            ShabbosChazon => "ShabbosChazon",
            ShabbosNachamu => "ShabbosNachamu",
            LeilSlichos => "LeilSlichos",
            ShabbosShuva => "ShabbosShuva",
        }
    }
}
impl MyToString for MinorDays {
    fn to_string(&self, language: Language) -> &'static str {
        match language {
            Language::English => match self {
                //Generated from https://play.golang.org/p/HtWEMOgflMt
                MinorDays::Omer1 => "1st day of the Omer",
                MinorDays::Omer2 => "2nd day of the Omer",
                MinorDays::Omer3 => "3rd day of the Omer",
                MinorDays::Omer4 => "4th day of the Omer",
                MinorDays::Omer5 => "5th day of the Omer",
                MinorDays::Omer6 => "6th day of the Omer",
                MinorDays::Omer7 => "7th day of the Omer",
                MinorDays::Omer8 => "8th day of the Omer",
                MinorDays::Omer9 => "9th day of the Omer",
                MinorDays::Omer10 => "10th day of the Omer",
                MinorDays::Omer11 => "11th day of the Omer",
                MinorDays::Omer12 => "12th day of the Omer",
                MinorDays::Omer13 => "13th day of the Omer",
                MinorDays::Omer14 => "14th day of the Omer",
                MinorDays::Omer15 => "15th day of the Omer",
                MinorDays::Omer16 => "16th day of the Omer",
                MinorDays::Omer17 => "17th day of the Omer",
                MinorDays::Omer18 => "18th day of the Omer",
                MinorDays::Omer19 => "19th day of the Omer",
                MinorDays::Omer20 => "20th day of the Omer",
                MinorDays::Omer21 => "21st day of the Omer",
                MinorDays::Omer22 => "22nd day of the Omer",
                MinorDays::Omer23 => "23rd day of the Omer",
                MinorDays::Omer24 => "24th day of the Omer",
                MinorDays::Omer25 => "25th day of the Omer",
                MinorDays::Omer26 => "26th day of the Omer",
                MinorDays::Omer27 => "27th day of the Omer",
                MinorDays::Omer28 => "28th day of the Omer",
                MinorDays::Omer29 => "29th day of the Omer",
                MinorDays::Omer30 => "30th day of the Omer",
                MinorDays::Omer31 => "31st day of the Omer",
                MinorDays::Omer32 => "32nd day of the Omer",
                MinorDays::Omer33 => "33rd day of the Omer",
                MinorDays::Omer34 => "34th day of the Omer",
                MinorDays::Omer35 => "35th day of the Omer",
                MinorDays::Omer36 => "36th day of the Omer",
                MinorDays::Omer37 => "37th day of the Omer",
                MinorDays::Omer38 => "38th day of the Omer",
                MinorDays::Omer39 => "39th day of the Omer",
                MinorDays::Omer40 => "40th day of the Omer",
                MinorDays::Omer41 => "41st day of the Omer",
                MinorDays::Omer42 => "42nd day of the Omer",
                MinorDays::Omer43 => "43rd day of the Omer",
                MinorDays::Omer44 => "44th day of the Omer",
                MinorDays::Omer45 => "45th day of the Omer",
                MinorDays::Omer46 => "46th day of the Omer",
                MinorDays::Omer47 => "47th day of the Omer",
                MinorDays::Omer48 => "48th day of the Omer",
                MinorDays::Omer49 => "49th day of the Omer",
                MinorDays::ErevPesach => "Erev Pesach",
                MinorDays::ErevSukkos => "Erev Sukkos",
                MinorDays::ErevShavuos => "Erev Shavuos",
                MinorDays::ErevYomKippur => "Erev Yom Kippur",
                MinorDays::ErevRoshHashanah => "Erev Rosh Hashana",
                MinorDays::PesachSheni => "Pesach Sheni",
                MinorDays::LagBaOmer => "Lag BaOmer",
                MinorDays::FifteenAv => "15th of Av",
                MinorDays::FifteenShvat => "15th of Shevat",
                MinorDays::PurimKattan => "Purim Kattan",
                MinorDays::ShushanPurimKattan => "Shushan Purim Kattan",
                MinorDays::ShabbosHaGadol => "Shabbos HaGadol",
                MinorDays::TaanisBechoros => "Taanis Bechoros",
                MinorDays::ShabbosChazon => "Shabbos Chazon",
                MinorDays::ShabbosNachamu => "Shabbos Nachamu",
                MinorDays::LeilSlichos => "Leil Slichos",
                MinorDays::ShabbosShuva => "Shabbos Shuva",
            },
            Language::Hebrew => match self {
                //generated from https://play.golang.org/p/LH0qQmYxZsP
                MinorDays::Omer1 => "היום יום 1 לעומר",
                MinorDays::Omer2 => "היום יום 2 לעומר",
                MinorDays::Omer3 => "היום יום 3 לעומר",
                MinorDays::Omer4 => "היום יום 4 לעומר",
                MinorDays::Omer5 => "היום יום 5 לעומר",
                MinorDays::Omer6 => "היום יום 6 לעומר",
                MinorDays::Omer7 => "היום יום 7 לעומר",
                MinorDays::Omer8 => "היום יום 8 לעומר",
                MinorDays::Omer9 => "היום יום 9 לעומר",
                MinorDays::Omer10 => "היום יום 10 לעומר",
                MinorDays::Omer11 => "היום יום 11 לעומר",
                MinorDays::Omer12 => "היום יום 12 לעומר",
                MinorDays::Omer13 => "היום יום 13 לעומר",
                MinorDays::Omer14 => "היום יום 14 לעומר",
                MinorDays::Omer15 => "היום יום 15 לעומר",
                MinorDays::Omer16 => "היום יום 16 לעומר",
                MinorDays::Omer17 => "היום יום 17 לעומר",
                MinorDays::Omer18 => "היום יום 18 לעומר",
                MinorDays::Omer19 => "היום יום 19 לעומר",
                MinorDays::Omer20 => "היום יום 20 לעומר",
                MinorDays::Omer21 => "היום יום 21 לעומר",
                MinorDays::Omer22 => "היום יום 22 לעומר",
                MinorDays::Omer23 => "היום יום 23 לעומר",
                MinorDays::Omer24 => "היום יום 24 לעומר",
                MinorDays::Omer25 => "היום יום 25 לעומר",
                MinorDays::Omer26 => "היום יום 26 לעומר",
                MinorDays::Omer27 => "היום יום 27 לעומר",
                MinorDays::Omer28 => "היום יום 28 לעומר",
                MinorDays::Omer29 => "היום יום 29 לעומר",
                MinorDays::Omer30 => "היום יום 30 לעומר",
                MinorDays::Omer31 => "היום יום 31 לעומר",
                MinorDays::Omer32 => "היום יום 32 לעומר",
                MinorDays::Omer33 => "היום יום 33 לעומר",
                MinorDays::Omer34 => "היום יום 34 לעומר",
                MinorDays::Omer35 => "היום יום 35 לעומר",
                MinorDays::Omer36 => "היום יום 36 לעומר",
                MinorDays::Omer37 => "היום יום 37 לעומר",
                MinorDays::Omer38 => "היום יום 38 לעומר",
                MinorDays::Omer39 => "היום יום 39 לעומר",
                MinorDays::Omer40 => "היום יום 40 לעומר",
                MinorDays::Omer41 => "היום יום 41 לעומר",
                MinorDays::Omer42 => "היום יום 42 לעומר",
                MinorDays::Omer43 => "היום יום 43 לעומר",
                MinorDays::Omer44 => "היום יום 44 לעומר",
                MinorDays::Omer45 => "היום יום 45 לעומר",
                MinorDays::Omer46 => "היום יום 46 לעומר",
                MinorDays::Omer47 => "היום יום 47 לעומר",
                MinorDays::Omer48 => "היום יום 48 לעומר",
                MinorDays::Omer49 => "היום יום 49 לעומר",
                MinorDays::ErevPesach => "ערב פסח",
                MinorDays::ErevSukkos => "ערב סוכות",
                MinorDays::ErevShavuos => "ערב שבועות",
                MinorDays::ErevYomKippur => "ערב יום כיפור",
                MinorDays::ErevRoshHashanah => "ערב ראש השנה",
                MinorDays::PesachSheni => "ערב פסח שני",
                MinorDays::LagBaOmer => "ל\"ג בעומר",
                MinorDays::FifteenAv => "ט\"ו באב",
                MinorDays::FifteenShvat => "ט\"ו בשבט",
                MinorDays::PurimKattan => "פורים קטן",
                MinorDays::ShushanPurimKattan => "שושן פורים קטן",
                MinorDays::ShabbosHaGadol => "שבת הגדול",
                MinorDays::TaanisBechoros => "תענית בכורות",
                MinorDays::ShabbosChazon => "שבת חזון",
                MinorDays::ShabbosNachamu => "שבת נחמו",
                MinorDays::LeilSlichos => "ליל סליחות",
                MinorDays::ShabbosShuva => "שבת שובה",
            },
        }
    }
}

//generated from https://play.golang.com/p/fCtYz6kNCBw
pub(crate) fn get_omer(year: &HebrewYear) -> [DayVal; 49] {
    use std::num::NonZeroI8;
    let first_day_of_pesach: DateTime<Utc> = year
        .get_hebrew_date(HebrewMonth::Nissan, NonZeroI8::new(15).unwrap())
        .unwrap()
        .into();

    //generated by https://play.golang.org/p/G78vf0EJnCN
    [
        DayVal {
            day: first_day_of_pesach + Duration::days(1),
            name: Name::MinorDays(MinorDays::Omer1),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(2),
            name: Name::MinorDays(MinorDays::Omer2),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(3),
            name: Name::MinorDays(MinorDays::Omer3),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(4),
            name: Name::MinorDays(MinorDays::Omer4),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(5),
            name: Name::MinorDays(MinorDays::Omer5),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(6),
            name: Name::MinorDays(MinorDays::Omer6),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(7),
            name: Name::MinorDays(MinorDays::Omer7),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(8),
            name: Name::MinorDays(MinorDays::Omer8),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(9),
            name: Name::MinorDays(MinorDays::Omer9),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(10),
            name: Name::MinorDays(MinorDays::Omer10),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(11),
            name: Name::MinorDays(MinorDays::Omer11),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(12),
            name: Name::MinorDays(MinorDays::Omer12),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(13),
            name: Name::MinorDays(MinorDays::Omer13),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(14),
            name: Name::MinorDays(MinorDays::Omer14),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(15),
            name: Name::MinorDays(MinorDays::Omer15),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(16),
            name: Name::MinorDays(MinorDays::Omer16),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(17),
            name: Name::MinorDays(MinorDays::Omer17),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(18),
            name: Name::MinorDays(MinorDays::Omer18),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(19),
            name: Name::MinorDays(MinorDays::Omer19),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(20),
            name: Name::MinorDays(MinorDays::Omer20),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(21),
            name: Name::MinorDays(MinorDays::Omer21),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(22),
            name: Name::MinorDays(MinorDays::Omer22),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(23),
            name: Name::MinorDays(MinorDays::Omer23),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(24),
            name: Name::MinorDays(MinorDays::Omer24),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(25),
            name: Name::MinorDays(MinorDays::Omer25),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(26),
            name: Name::MinorDays(MinorDays::Omer26),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(27),
            name: Name::MinorDays(MinorDays::Omer27),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(28),
            name: Name::MinorDays(MinorDays::Omer28),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(29),
            name: Name::MinorDays(MinorDays::Omer29),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(30),
            name: Name::MinorDays(MinorDays::Omer30),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(31),
            name: Name::MinorDays(MinorDays::Omer31),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(32),
            name: Name::MinorDays(MinorDays::Omer32),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(33),
            name: Name::MinorDays(MinorDays::Omer33),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(34),
            name: Name::MinorDays(MinorDays::Omer34),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(35),
            name: Name::MinorDays(MinorDays::Omer35),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(36),
            name: Name::MinorDays(MinorDays::Omer36),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(37),
            name: Name::MinorDays(MinorDays::Omer37),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(38),
            name: Name::MinorDays(MinorDays::Omer38),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(39),
            name: Name::MinorDays(MinorDays::Omer39),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(40),
            name: Name::MinorDays(MinorDays::Omer40),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(41),
            name: Name::MinorDays(MinorDays::Omer41),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(42),
            name: Name::MinorDays(MinorDays::Omer42),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(43),
            name: Name::MinorDays(MinorDays::Omer43),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(44),
            name: Name::MinorDays(MinorDays::Omer44),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(45),
            name: Name::MinorDays(MinorDays::Omer45),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(46),
            name: Name::MinorDays(MinorDays::Omer46),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(47),
            name: Name::MinorDays(MinorDays::Omer47),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(48),
            name: Name::MinorDays(MinorDays::Omer48),
            candle_lighting: None,
        },
        DayVal {
            day: first_day_of_pesach + Duration::days(49),
            name: Name::MinorDays(MinorDays::Omer49),
            candle_lighting: None,
        },
    ]
}
